version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redisInsight
    ports:
      - "8001:8001"

  post_db:
    image: postgres:14.1-alpine
    container_name: post_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local