version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redisInsight
    ports:
      - "8001:8001"